// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rota.Api.Data;

#nullable disable

namespace Rota.Api.Migrations
{
    [DbContext(typeof(RotaDbContext))]
    partial class RotaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Rota.Api.Domain.RouteRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Optimization")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId");

                    b.ToTable("RouteRequests");
                });

            modelBuilder.Entity("Rota.Api.Domain.RouteResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RouteRequestId")
                        .HasColumnType("int");

                    b.Property<string>("SerializedPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TotalDistanceKm")
                        .HasColumnType("float");

                    b.Property<double>("TotalTimeMinutes")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("RouteRequestId");

                    b.ToTable("RouteResults");
                });

            modelBuilder.Entity("Rota.Api.Domain.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("CostPerHour")
                        .HasColumnType("float");

                    b.Property<double>("CostPerKm")
                        .HasColumnType("float");

                    b.Property<double>("DriverCostPerHour")
                        .HasColumnType("float");

                    b.Property<double>("MaxDistanceWithoutRefuelKm")
                        .HasColumnType("float");

                    b.Property<double>("MaxHeightM")
                        .HasColumnType("float");

                    b.Property<double>("MaxLoadWeightKg")
                        .HasColumnType("float");

                    b.Property<double>("MaxVolumeM3")
                        .HasColumnType("float");

                    b.Property<double>("MaxWeightKg")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Vehicle");
                });

            modelBuilder.Entity("Rota.Api.Domain.Waypoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int?>("RouteRequestId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RouteRequestId");

                    b.ToTable("Waypoints");
                });

            modelBuilder.Entity("Rota.Api.Domain.RouteRequest", b =>
                {
                    b.HasOne("Rota.Api.Domain.Vehicle", "Vehicle")
                        .WithMany("RouteRequests")
                        .HasForeignKey("VehicleId");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("Rota.Api.Domain.RouteResult", b =>
                {
                    b.HasOne("Rota.Api.Domain.RouteRequest", "RouteRequest")
                        .WithMany("Results")
                        .HasForeignKey("RouteRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RouteRequest");
                });

            modelBuilder.Entity("Rota.Api.Domain.Waypoint", b =>
                {
                    b.HasOne("Rota.Api.Domain.RouteRequest", null)
                        .WithMany("Waypoints")
                        .HasForeignKey("RouteRequestId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Rota.Api.Domain.RouteRequest", b =>
                {
                    b.Navigation("Results");

                    b.Navigation("Waypoints");
                });

            modelBuilder.Entity("Rota.Api.Domain.Vehicle", b =>
                {
                    b.Navigation("RouteRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
